import os

DATABASE_DSN = os.environ["DATABASE_DSN"]
AUTO_RELOAD = os.environ["AUTO_RELOAD"]
PASSWORD_SALT = os.environ["PASSWORD_SALT"]
COOKIE_SECRET_KEY = os.environ["COOKIE_SECRET_KEY"]
WEBHOOK_SECRET_KEY = os.environ["WEBHOOK_SECRET_KEY"]
